apiVersion: apps/v1
kind: Deployment
metadata:
  name: madi-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: madi-api
  template:
    metadata:
      labels:
        app: madi-api
    spec:
      containers:
      - name: madi-api
        image: us-docker.pkg.dev/dark-gateway-365319/madi-api/api-test
        ports:
          - containerPort: 3000
        resources:
          limits:
            cpu: ".5"
            memory: "500Mi"
          requests:
            cpu: ".25"
            memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10